services:
  teacher_panel:
    build:
      context: ./teacher-panel
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true

  websocket-server:
    build:
      context: ./websocket-server
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - WATCHPACK_POLLING=true
    command: yarn start

  postgre-api:
    build:
      context: ./postgre-api
      dockerfile: Dockerfile
    volumes:
      - ./postgre-api:/app
      - /app/node_modules
    ports:
      - "3030:3030"
    environment:
      - WATCHPACK_POLLING=true
    command: yarn start

  postgre-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      DATABASE_PORT: 5432
      POSTGRES_DB: postgres_thesis
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    user: "root"

volumes:
  db-data:
